name: Docker Build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Docker Image
    steps:
      - uses: actions/checkout@v3
      - id: imgtagger
        run: |
          imgtags=$(echo "${{ github.ref }}" | sed 's/refs\/tags\//latest,/; s/refs\/heads\///')
          echo "{imgtags}={$imgtags}" >> $GITHUB_OUTPUT
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: "${{ steps.imgtagger.outputs.imgtags }}"
