name: "Comment Run"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  comment-run:
    if: contains(github.event.comment.body, '@github-actions run')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code (Deep)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up IPFS and Rub Daemon
      uses: oduwsdl/setup-ipfs@main
      with:
        run_daemon: true
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install Test Dependencies
      run: pip install -r test-requirements.txt
    - name: Install IPWB from Source
      run: pip install .
    - name: Execute Code in Comment
      uses: ibnesayeed/actions-comment-run@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        allowed-associations: '["OWNER", "MEMBER"]'
