name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    name: Py and JS
    steps:
      - uses: actions/checkout@v4
      - name: Lint JavaScript
        run: |
          npm install standard
          node_modules/.bin/standard
      - name: Clean up standard.js artifacts
        shell: bash
        run: |
          rm -rf node_modules
          rm package-lock.json
          rm package.json
      - name: Lint Python
        run: |
          pip install --user pycodestyle
          python -m pycodestyle --max-line-length=88
